default: &default
  adapter: oracle_enhanced
  encoding: utf8
  # TNS descriptor format - more reliable for Oracle XE
  database: "(DESCRIPTION=
    (ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=oracle)(PORT=1521)))
    (CONNECT_DATA=(SERVICE_NAME=xepdb1))
  )"

development:
  <<: *default
  username: "invoice_app_<%= ENV.fetch('RAILS_ENV')%>_db"
  password: <%= ENV.fetch("ORACLE_PASSWORD", "developmentpass") %>

test:
  <<: *default
  username: "invoice_app_<%= ENV.fetch('RAILS_ENV')%>_db"
  password: <%= ENV.fetch("ORACLE_PASSWORD", "developmentpass") %>

production:
  <<: *default
  username: "invoice_app_<%= ENV.fetch('RAILS_ENV')%>_db"
  password: <%= ENV.fetch("ORACLE_PASSWORD", "developmentpass") %>